class ClaimsDashboardItems {
  const ClaimsDashboardItems({
    required this.requestNumber,
    required this.customerName,
    required this.carNumber,
    required this.carName,
    required this.status,
    required this.phoneNumber,
    required this.emailId,
  });

  final String requestNumber;
  final String customerName;
  final String carNumber;
  final String carName;
  final String status;
  final String phoneNumber;
  final String emailId;
}

List<ClaimsDashboardItems> dummyData = [
  const ClaimsDashboardItems(
    requestNumber: 'R123457890909090',
    customerName: 'John Doe',
    carNumber: 'ABC123',
    carName: 'Toyota Camry',
    status: 'Pending',
    phoneNumber: '123-456-7890',
    emailId: 'john.doe@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R67890',
    customerName: 'Jane Smith',
    carNumber: 'XYZ789',
    carName: 'Honda Accord',
    status: 'Completed',
    phoneNumber: '987-654-3210',
    emailId: 'jane.smith@example.com',
  ),
  const ClaimsDashboardItems(
      requestNumber: "R1234567",
      customerName: "Sameer",
      carNumber: "MH01SA0001",
      carName: "GClass",
      status: "Midway",
      phoneNumber: "9769253131",
      emailId: "sameer@gmail.com"),
  const ClaimsDashboardItems(
    requestNumber: 'R11111',
    customerName: 'Alice Johnson',
    carNumber: 'DEF456',
    carName: 'Ford Explorer',
    status: 'In Progress',
    phoneNumber: '555-123-4567',
    emailId: 'alice.johnson@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R22222',
    customerName: 'Bob Wilson',
    carNumber: 'GHI789',
    carName: 'Chevrolet Malibu',
    status: 'Pending',
    phoneNumber: '555-987-6543',
    emailId: 'bob.wilson@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R33333',
    customerName: 'Eva Martinez',
    carNumber: 'JKL012',
    carName: 'Nissan Altima',
    status: 'Completed',
    phoneNumber: '555-876-5432',
    emailId: 'eva.martinez@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R44444',
    customerName: 'David Lee',
    carNumber: 'MNO345',
    carName: 'Honda Civic',
    status: 'Pending',
    phoneNumber: '555-234-5678',
    emailId: 'david.lee@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R55555',
    customerName: 'Sophia White',
    carNumber: 'PQR678',
    carName: 'Kia Sportage',
    status: 'In Progress',
    phoneNumber: '555-345-6789',
    emailId: 'sophia.white@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R66666',
    customerName: 'Ryan Davis',
    carNumber: 'STU901',
    carName: 'Hyundai Sonata',
    status: 'Completed',
    phoneNumber: '555-789-0123',
    emailId: 'ryan.davis@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R77777',
    customerName: 'Emma Turner',
    carNumber: 'VWX234',
    carName: 'Ford Fusion',
    status: 'Pending',
    phoneNumber: '555-901-2345',
    emailId: 'emma.turner@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R88888',
    customerName: 'Daniel Brown',
    carNumber: 'YZA567',
    carName: 'Chevrolet Impala',
    status: 'In Progress',
    phoneNumber: '555-456-7890',
    emailId: 'daniel.brown@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R99999',
    customerName: 'Olivia Miller',
    carNumber: 'BCD890',
    carName: 'Toyota Corolla',
    status: 'Completed',
    phoneNumber: '555-012-3456',
    emailId: 'olivia.miller@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R10101',
    customerName: 'Ethan Clark',
    carNumber: 'EFG123',
    carName: 'Honda CR-V',
    status: 'Pending',
    phoneNumber: '555-234-5678',
    emailId: 'ethan.clark@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R11223',
    customerName: 'Ava Garcia',
    carNumber: 'HIJ456',
    carName: 'Nissan Rogue',
    status: 'In Progress',
    phoneNumber: '555-567-8901',
    emailId: 'ava.garcia@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R44556',
    customerName: 'Liam Martinez',
    carNumber: 'KLM789',
    carName: 'Ford Escape',
    status: 'Completed',
    phoneNumber: '555-890-1234',
    emailId: 'liam.martinez@example.com',
  ),
  const ClaimsDashboardItems(
    requestNumber: 'R77889',
    customerName: 'Mia Turner',
    carNumber: 'NOP012',
    carName: 'Chevrolet Equinox',
    status: 'Pending',
    phoneNumber: '555-123-4567',
    emailId: 'mia.turner@example.com',
  ),
];
